### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Abdullah-Haque** [sanjib-sen/bux-frontend#1]
![image](https://user-images.githubusercontent.com/66621223/127319868-b0b86c18-3fcb-4079-9030-9d68852c76ea.png)

![image](https://user-images.githubusercontent.com/66621223/127319959-ecb0401e-46f7-4590-b0ce-9e8bc83478c7.png)
`
 1 of 1 unhandled error

Unhandled Runtime Error
TypeError: Cannot read property 'length' of undefined

Source
.next\static\chunks\pages\dashboard.js (28:10) @ submitHandler

  26 | 
  27 | 	function submitHandler() {
> 28 | 		if (lst.length < 6) {
     | 		       ^
  29 | 			setWarning(null);
  30 | 			console.log(lst);
  31 | 			localStorage.setItem("courses", lst);
Call Stack
HTMLUnknownElement.callCallback
/_next/static/chunks/main.js (20695:14)
Object.invokeGuardedCallbackDev
.next\static\chunks\main.js (3994:0)
invokeGuardedCallback
/_next/static/chunks/main.js (20806:31)
invokeGuardedCallbackAndCatchFirstError
.next\static\chunks\main.js (4070:0)
executeDispatch
/_next/static/chunks/main.js (24993:3)
processDispatchQueueItemsInOrder
file:///D:/Downloads/Compressed/Project-bux-Reborn-master/.next/static/chunks/main.js (25025:7)
processDispatchQueue
/_next/static/chunks/main.js (25038:5)
dispatchEventsForPlugins
.next\static\chunks\main.js (8299:0)
<unknown>
/_next/static/chunks/main.js (25258:12)
batchedEventUpdates$1
.next\static\chunks\main.js (22396:0)
batchedEventUpdates
/_next/static/chunks/main.js (20495:12)
dispatchEventForPluginEventSystem
.next\static\chunks\main.js (8507:0)
attemptToDispatchEvent
/_next/static/chunks/main.js (22755:3)
dispatchEvent
.next\static\chunks\main.js (5924:0)
unstable_runWithPriority
/_next/static/chunks/main.js (47265:12)
runWithPriority$1
file:///D:/Downloads/Compressed/Project-bux-Reborn-master/.next/static/chunks/main.js (28026:10)
discreteUpdates$1
/_next/static/chunks/main.js (39158:14)
discreteUpdates
file:///D:/Downloads/Compressed/Project-bux-Reborn-master/.next/static/chunks/main.js (20506:12)
dispatchDiscreteEvent
/_next/static/chunks/main.js (22639:3)
Hide collapsed frames`

![image](https://user-images.githubusercontent.com/66621223/127320103-3fdce3e3-bbd5-4818-9331-dc2743e4f694.png)

`Microsoft Windows [Version 10.0.19041.421]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd "D:\Downloads\Compressed\Project-bux-Reborn-master"

C:\WINDOWS\system32>cd \d "D:\Downloads\Compressed\Project-bux-Reborn-master"
The filename, directory name, or volume label syntax is incorrect.

C:\WINDOWS\system32>cd /d "D:\Downloads\Compressed\Project-bux-Reborn-master"

D:\Downloads\Compressed\Project-bux-Reborn-master>npm install
npm WARN deprecated querystring@0.2.1: The
npm WARN deprecated querystring@0.2.0: The

> puppeteer@10.1.0 install D:\Downloads\Compressed\Project-bux-Reborn-master\node_modules\puppeteer
> node install.js

Downloading Chromium r884014 - 169.7 Mb [====================] 99% 0.0s
Chromium (884014) downloaded to D:\Downloads\Compressed\Project-bux-Reborn-master\node_modules\puppeteer\.local-chromium\win64-884014
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN next@11.0.1 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN next@11.0.1 requires a peer of node-sass@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN next@11.0.1 requires a peer of sass@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @next/react-refresh-utils@11.0.1 requires a peer of webpack@^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.6 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.6 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 353 packages from 291 contributors in 81.447s

52 packages are looking for funding
  run `npm fund` for details

D:\Downloads\Compressed\Project-bux-Reborn-master>npm run dev

> bux@4.0.0 dev D:\Downloads\Compressed\Project-bux-Reborn-master
> next

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
The static directory has been deprecated in favor of the public directory. https://nextjs.org/docs/messages/static-dir-deprecated
event - compiled successfully
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

event - build page: /
wait  - compiling...
event - compiled successfully
Material-UI: the createMuiTheme function was renamed to createTheme.

You should use `import { createTheme } from '@material-ui/core/styles'`
event - build page: /login
wait  - compiling...
event - build page: /next/dist/pages/_error
Material-UI: the createMuiTheme function was renamed to createTheme.

You should use `import { createTheme } from '@material-ui/core/styles'`
event - compiled successfully
Material-UI: the createMuiTheme function was renamed to createTheme.

You should use `import { createTheme } from '@material-ui/core/styles'`
wait  - compiling...
event - compiled successfully
event - build page: /api/login
wait  - compiling...
event - compiled successfully
event - build page: /dashboard
wait  - compiling...
event - compiled successfully
Material-UI: the createMuiTheme function was renamed to createTheme.

You should use `import { createTheme } from '@material-ui/core/styles'`
Warning: Failed prop type: Invalid prop `variant` of value `inherit` supplied to `ForwardRef(Button)`, expected one of ["contained","outlined","text"].
    at Button (D:\Downloads\Compressed\Project-bux-Reborn-master\.next\server\pages\dashboard.js:1754:24)
    at WithStyles(ForwardRef(Button)) (D:\Downloads\Compressed\Project-bux-Reborn-master\node_modules\@material-ui\styles\withStyles\withStyles.js:67:31)
    at div
    at Toolbar (D:\Downloads\Compressed\Project-bux-Reborn-master\.next\server\pages\dashboard.js:2807:23)
    at WithStyles(ForwardRef(Toolbar)) (D:\Downloads\Compressed\Project-bux-Reborn-master\node_modules\@material-ui\styles\withStyles\withStyles.js:67:31)
    at header
    at Paper (D:\Downloads\Compressed\Project-bux-Reborn-master\.next\server\pages\dashboard.js:2444:23)
    at WithStyles(ForwardRef(Paper)) (D:\Downloads\Compressed\Project-bux-Reborn-master\node_modules\@material-ui\styles\withStyles\withStyles.js:67:31)
    at AppBar (D:\Downloads\Compressed\Project-bux-Reborn-master\.next\server\pages\dashboard.js:367:23)
    at WithStyles(ForwardRef(AppBar)) (D:\Downloads\Compressed\Project-bux-Reborn-master\node_modules\@material-ui\styles\withStyles\withStyles.js:67:31)
    at div
    at AppNavBar (D:\Downloads\Compressed\Project-bux-Reborn-master\.next\server\pages\dashboard.js:6341:19)
    at div
    at DataTable (D:\Downloads\Compressed\Project-bux-Reborn-master\.next\server\pages\dashboard.js:6527:54)
    at ThemeProvider (D:\Downloads\Compressed\Project-bux-Reborn-master\node_modules\@material-ui\styles\ThemeProvider\ThemeProvider.js:48:24)
    at MyApp (D:\Downloads\Compressed\Project-bux-Reborn-master\.next\server\pages\_app.js:2654:5)
    at StylesProvider (D:\Downloads\Compressed\Project-bux-Reborn-master\node_modules\@material-ui\styles\StylesProvider\StylesProvider.js:57:24)
    at AppContainer (D:\Downloads\Compressed\Project-bux-Reborn-master\node_modules\next\dist\next-server\server\render.js:27:952)
event - build page: /api/dashboard
wait  - compiling...
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
Material-UI: the createMuiTheme function was renamed to createTheme.

You should use `import { createTheme } from '@material-ui/core/styles'`
wait  - compiling...
event - compiled successfully

Could not open dashboard.js in the editor.

To set up the editor integration, add something like REACT_EDITOR=atom to the .env.local file in your project folder and restart the development server.

Could not open dashboard.js in the editor.

To set up the editor integration, add something like REACT_EDITOR=atom to the .env.local file in your project folder and restart the development server.

Could not open dashboard.js in the editor.

To set up the editor integration, add something like REACT_EDITOR=atom to the .env.local file in your project folder and restart the development server.

Could not open dashboard.js in the editor.

To set up the editor integration, add something like REACT_EDITOR=atom to the .env.local file in your project folder and restart the development server.

`

**Comment by sanjib-sen** [comment]
Working on this. Just give me some hours!

**Comment by Abdullah-Haque** [comment]
Thanks for the swift response dev @sanjib-sen

**Comment by sanjib-sen** [comment]
@Abdullah-Haque Can you please check it now? It has been fixed.
To update your downloaded repo: simply type on console/cmd/powershell (git must be installed)  from the downloaded directory: 

```bash
git pull
```
and you are good to go. 
Or just redownload the repository.

**Comment by Abdullah-Haque** [comment]
Thanks it's working now!!! @sanjib-sen

**Comment by sanjib-sen** [comment]
@Abdullah-Haque You are welcome!
Let me know if you face any problem. Or have any feedback!

**Comment by Abdullah-Haque** [comment]
Sure!!!
