### ISSUE TITLE
[Feature Request] Provide Script for Automation

### ISSUE THREAD

**Issue by Abdullah-Haque** [sanjib-sen/bux-frontend#2]
Hi there @sanjib-sen , it would be helpful to provide batch file/ powershell script to automate the process...for example starting the server and opening up the login page in default browser with a single click?
TIA

**Comment by sanjib-sen** [comment]
Thanks for the suggestion. I am working on that!

**Comment by sanjib-sen** [comment]
@Abdullah-Haque 

Added a PowerShell script. Also created an .exe file for convenience.

Instructions:
1. Update
 ```bash
    git pull
 ```

2. Run BUX.exe
3. You can also create a shortcut for BUX.exe in Desktop by Right-Clicking on BUX.exe > Create Shortcut. That should work too. (Don't copy/cut the actual BUX.exe, it won't work. You can copy/cut the shortcut file though)

Let me know if that works.

**Comment by Abdullah-Haque** [comment]
Works like a charm 👌😍💯🔥
